In [1]:
import numpy as np
from numpy import genfromtxt

data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
# data

In [5]:
labels = data[:,-1]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [10]:
features = data[:,:-1]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X = features
y = labels

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [18]:
#Standardizing the data
from sklearn.preprocessing import MinMaxScaler

scaler_object = MinMaxScaler()

scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
scaled_X_train = scaler_object.transform(X_train)

In [23]:
scaled_X_test = scaler_object.transform(X_test)

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()

model.add(Dense(4,input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 1s - loss: 0.7228 - acc: 0.3308
Epoch 2/50
 - 0s - loss: 0.7057 - acc: 0.4298
Epoch 3/50
 - 0s - loss: 0.6951 - acc: 0.5223
Epoch 4/50
 - 0s - loss: 0.6875 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6822 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6779 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6735 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6694 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6645 - acc: 0.5495
Epoch 10/50
 - 0s - loss: 0.6595 - acc: 0.5702
Epoch 11/50
 - 0s - loss: 0.6534 - acc: 0.5985
Epoch 12/50
 - 0s - loss: 0.6472 - acc: 0.6322
Epoch 13/50
 - 0s - loss: 0.6410 - acc: 0.6561
Epoch 14/50
 - 0s - loss: 0.6339 - acc: 0.6627
Epoch 15/50
 - 0s - loss: 0.6260 - acc: 0.6801
Epoch 16/50
 - 0s - loss: 0.6172 - acc: 0.6855
Epoch 17/50
 - 0s - loss: 0.6068 - acc: 0.6899
Epoch 18/50
 - 0s - loss: 0.5961 - acc: 0.6899
Epoch 19/50
 - 0s - loss: 0.5851 - acc: 0.6910
Epoch 20/50
 - 0s - loss: 0.5740 - acc: 0.7062
Epoch 21/50
 - 0s - loss: 0.5623 - acc: 0.7323
Epoch 22/50
 - 0s - lo

In [28]:
# model.predict_classes(scaled_X_test)

In [29]:
# model.metrics_names

['loss', 'acc']

In [30]:
from sklearn.metrics import confusion_matrix, classification_report
results = model.predict_classes(scaled_X_test)

In [31]:
confusion_matrix(y_test, results)

array([[256,   1],
       [ 17, 179]], dtype=int64)

In [33]:
print(classification_report(y_test, results))

             precision    recall  f1-score   support

        0.0       0.94      1.00      0.97       257
        1.0       0.99      0.91      0.95       196

avg / total       0.96      0.96      0.96       453



In [34]:
model.save('My_model.h5')

In [35]:
from keras.models import load_model
newmodel = load_model('My_model.h5')

In [36]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    